
clientes_perfil = {'azeneth',
                   'Morales',
                   'Angelica',
                   'Ana pau ',
                   'Señora ',
                   'Ana maria ',
                   'Norma Lopez',
                   'esposa gemelo',
                   'Margarita',
                   'Manita',
                   'Abuelita eli ',
                   'EVA ',
                   'Francisco ',
                   'elvia',
                   'Aana maria',
                   'Elli',

                   'Biyik ',
                   'Juan carlos ',
                   'clienta-35',
                   'mauricio',
                   'Verónica ',
                   'Mellisa Aguilar',
                   'Cristal ',
                   'ellie',
                   'Ale-20-A',
                   'Cris  ',
                   'Marcela',
                   'Joaquin',
                   'Extrem',
                   'Duadalupe',
                   'Judith',
                   'Angeles ',
                   'Cliente 11',
                   'Jenifer',
                   'Jessica ',
                   'Azahalea',
                   'Joaco 2',
                   'Sra-Gloria',
                   'Tacos el vecino',
                   'Francisco',
                   'Dias',
                   'marcos',
                   'Portales 42',
                   'barbero',
                   '34b-503',
                   'francisco',
                   'cli17',
                   'elem',
                   'Abuela yayo ',
                   'Irvin ',
                   'alejandra-7a',
                   'Balbelo',
                   'Ester',
                   'Biyik',
                   'Serranita ',
                   'Andrea-Valeriano',
                   'Fernando cli ',
                   'panadero',
                   'Irma-Gutierez',
                   'Nacia ',
                   'biyi',
                   'johana',
                   '9b depto 101',
                   'Isabell',
                   'Joahana',
                   'Sr Nava',
                   'Monica ',
                   'Juanita',
                   'aylin',
                   'tacos el vecino',
                   'karla',
                   'Cliente-20',
                   'Sr juarez ',
                   'Clienta-portales21',
                   'Azahalea ',
                   'Carlos galindo',
                   'Irving ',
                   'Carlos',
                   'Emma ',
                   'Carolina ',
                   'Oscare',
                   'Gerardo ',
                   'Socorro',
                   'Pastor ',
                   'Alejadra-20a',
                   'Portales 39',
                   'Emms ',
                   'Mosco',
                   'tacos vecinos',
                   'micha',
                   'Angelica ',
                   ' Cliente 11 ',
                   'Fernanda-Lopez',
                   'Ailyn',
                   'Ale-20a',
                   'Mauricio',
                   'sami',
                   'Purisima ',
                   'Cliente-Tortas',
                   'Cliente 17',
                   'Amelia',
                   'Tío biyik',
                   'Alejandra-9b',
                   'Aguaqliva',
                   'Max ',
                   'edith',
                   'Johana-19b',
                   'Monserrat',
                   'clienta messinger',
                   'Rea',
                   'ivan',
                   'Bikiy ',
                   'Adeli',
                   'juarez',
                   'irma',
                   'Ester ',
                   'azahalea',
                   'Puesto pansita',
                   'Miriam',
                   'Clienta16',
                   'Cliente 4 ',
                   'Cliente-18',
                   'eli',
                   'Emms',
                   'Maria-Luisa',
                   'gerardo',
                   'Carlos-galindo',
                   'Pastrano',
                   'Adonqueli ',
                   'may rodriges ',
                   'Luis Rojas',
                   'Tata',
                   'Serranita',
                   'ana maria ',
                   'cliente 11',
                   'cli purisima',
                   'Clauidia',
                   'Bellako',
                   'joaco',
                   'Josue',
                   'Irvin',
                   'Cliente torta',
                   'josue',
                   'Angélica',
                   'Ceci',
                   '13a',
                   'Jorge ',
                   'Eva ',
                   'Yair',
                   'azeet',
                   'juan carlos',
                   'Cliente 16 ',
                   'Local-Uñas',
                   'Purisima11',
                   'juan c',
                   'May',
                   'Cliente-edificio11a',
                   'Socorro ',
                   'Oscar',
                   'tierno',
                   'portales42',
                   'Guadalupe',
                   'Acua-Cliva',
                   'Hacienda castañeda 20',
                   'Frida',
                   'Azul ',
                   'rita',
                   'Ximena ',
                   'Marialusa',
                   'cliente  ',
                   'Maria-luisa',
                   'Elvia Vazuquez',
                   'naci',
                   'San isidro ',
                   'Mitzi ',
                   'Veronica',
                   'Maria',
                   'Gerardo-Portales ',
                   'Braulio',
                   'angelica',
                   'Melissa',
                   'Barbero',
                   'Braulio ',
                   'irvin ',
                   'barber',
                   'Azeneth',
                   'Andrea',
                   'Chato',
                   'Cliente-torta',
                   'aylin ',
                   'Karina',
                   'Alejandra-Portales',
                   'Gemelo',
                   'Edificio 36 a ',
                   'Alonso',
                   'Matas',
                   'Azenet',
                   'carlos galindo ',
                   'edgar',
                   'May rodriguez',
                   'cliente 18',
                   'Aale',
                   'joaquin',
                   'Elia-aguilar',
                   'Mi niño ',
                   'Mitt',
                   'Eliseo ',
                   'Cliente-48',
                   'Edgar ',
                   'Azhalaea',
                   'Adonqueli',
                   'barber ',
                   'America Bolañoz',
                   'America-Bolaños',
                   'claudia',
                   'Rockz',
                   'Mauricio-Bravo',
                   'Aalejandra',
                   'Muaricio-Bravo',
                   'Portales 7',
                   'Clienta 23',
                   'Alejandra-castañeda',
                   'Ale  ',
                   'luisa',
                   'laraa',
                   'Esposa gemelo ',
                   'Ramirez',
                   'Franciasco ',
                   'Jeesica',
                   'Anabel',
                   'biyik',
                   'Jonathan',
                   'jafet',
                   'norma ',
                   'ale',
                   'Mauricio Bravo ',
                   'mata',
                   'ivi',
                   'erika',
                   'Mauricio bravo ',
                   'Tere',
                   'tavo',
                   'Cinthya ',
                   'Xtrem',
                   'Carlos galindo ',
                   'Devil',
                   'tacos ',
                   'Tacos vecino',
                   'Carlos ',
                   'Mauricio Bravo',
                   'Franciisco ',
                   'Perla',
                   'Norma',
                   'joaco ',
                   'Fernanda ',
                   'Norma padron',
                   'fernan',
                   'carlos galindo',
                   'Lupita',
                   'Iglesia ',
                   'Moises',
                   'Mary rodriguez',
                   'angel carne',
                   'kelly velez',
                   'Gabriela',
                   'Zoe ',
                   'Elivia',
                   'Mariposa ',
                   'Edgar',
                   'Veronica ',
                   'cliente 17',
                   'Roa',
                   'Portales 39 ',
                   'berber',
                   'Yayo',
                   'ale ',
                   'Ingrid',
                   'Fer ',
                   'jessica',
                   'cli 17B',
                   'Laraa',
                   'Alejandra-20a',
                   'Patrano ',
                   'Sra-juarez',
                   'irvin',
                   'Marcos tienda',
                   'Zona',
                   'Rea ',
                   'Azhalahea',
                   'Cliente 18 ',
                   'Clienta 36 ',
                   'Blanca',
                   'Aangelica',
                   'Carlos-6a',
                   'Betzabe',
                   'ema',
                   'francisco ',
                   'Cliente-67',
                   'irma ',
                   'Cliente20b',
                   'Gemelo ',
                   'Alejandra-portales7',
                   'norma',
                   'Clienta-6a404',
                   'An-maria',
                   'Jair',
                   'Paola-San-Isidro',
                   'Cristina',
                   'Oscar ',
                   'Alejandra-844',
                   'Alejandra-portales',
                   'yayo',
                   'eva',
                   'hector ',
                   'Elma',
                   'Carlos-Galindo',
                   'Zacarias',
                   'Andre-Valeriano',
                   'Rocio-Martinez',
                   'Cliente 18 a ',
                   'Angi',
                   'Pastrano ',
                   'cuervo',
                   'PURISIMA-11', 'cliente-18', 'oscar', 'Norma ', 'Carla', 'alejandra-portales7', 'Jasleg', 'Gauadalupe', 'Norma-Lopez', 'Anita-Duran', 'yair', 'mauricio ', 'Clienta 48 ', 'Juarez', 'Johana', 'Alicia ', 'azhalae', 'Milsen ', 'Tierno', 'Adoqueli ', 'yayo ', 'Cliente 17 ', 'Edith ', 'tacos-vecino', '=+D22', 'Ana Pau', 'Alejandra 7a ', 'hector', 'Ncia ureña', 'Ana', 'Martina ', 'Gerardo', 'Jorge cli ', 'America-44a', 'Buba', 'Clauida ', 'Maria-Garcia', 'Cliente 13', 'gemelo', 'Angel', 'Fernan', 'Luisa', 'Mauricio reyes ', 'tia wuacho', 'Cliente-san isidro', 'juaco', 'Irma', 'Cliente-16', 'May Rodriguez', 'Victoria', 'Aamerica Bolaños', 'Castañeda', 'Cliente-6a102', 'chato', 'jaula', 'Acua-cliva', 'Bertha', 'ELI ABUE', 'Javier', 'Olga', 'iv 8a 304', ' Mauricio-Bravo', ' Balbelo ', '20a ', 'laura', 'America Bolaños', 'Isabel ', 'alyn', 'Ale', 'Mauricio ', 'Elia-Aguilar', 'Scarlett', 'Sandra', 'laara', 'Micha', 'fernanda', 'Cliente buba', 'Clinte 18', 'Guada mocte ', 'Purisima 11', 'eliseo', 'cli 6a 102', 'tacos vecino', 'Bub', 'Ruth', 'alejandra-portales', 'Carlos Galindo', 'Melissa galindo', 'alejandra', 'braulio', 'Azahale', 'tio biyi', 'Teresa', 'Mar', 'Cliente-31', '6 a depto 404', 'Extrem ', 'Clienta-17', 'Monica', 'Ricardo', 'Cliente m ', 'Marcos', 'kardis', 'No especificado', 'Ana Maria ', 'Ruth ', 'Pelon', 'pelon', 'Alejandra-7a', 'Cliente-17', 'Ericka', 'Esmeralda', 'adonqueli', 'Cinthia cli ', 'May', 'Tacos el vecino ', 'Babo ', 'tio biyo', 'Erika', 'JOACO', 'Cliente_Sanisidro', 'Elia ', 'Cliente18', 'America', 'Cliente 8 ', 'alejandra-20a', 'Esme', 'azenet', 'Nava', 'Emelia', 'Brawlio ', 'Mar ', 'Ivanna', 'emms', 'Joaco', 'Tia eacho ', 'Cliente 18', 'iV-8a-304', 'Emma', 'Cliente-portales42', 'Rita', 'IV', 'ñirvin ', 'Gera', 'azhalaea', 'Laara ', 'Eli', 'Mauricio-bravo', 'mauricio-bravo', 'carlos ', 'Joaco ', 'Mario', 'serranita', 'Martina', 'Jose-Rojas', 'Julio-Servantes', 'brenda ', 'Aangelica ', 'Claudia', 'Laara', 'ahuatz', 'Azaahalea', 'Alejandra', '13A', ' Clauidia', 'America ', 'monica', 'Cliente-11', 'Alejandra-33a', 'Andrea valeriano', 'May ', 'ClientaP42', 'Cliente puri ', 'Melissa Aguilar', 'Ale ', 'Jessica', 'Moi', 'Tia wacho ', 'rea', 'Milsen', 'Zaragoza', 'Melisa ', 'Joaquin ', 'Zona ', 'Gfa eli ', 'May rodrigez', 'nacia', 'elma ', 'Moon', 'Azeneth ', 'melisa', 'Reina', 'Cliente 19', 'Eliseo', 'America Bolaños ', 'Amparo', 'Fernando', 'Kamila', 'Recluta', 'Nacia', 'Jorge', 'Ahuatz', 'jessica-portales', 'Kmpe', 'Fernanda navarro', 'Balbelo ', 'Purisima 11 ', 'cliente-14', 'Fernanda-lopez', 'Barber', 'tia wacho', 'Karla', 'german', 'Cliente-Torta', 'Arely', 'Chato ', 'Ana-maria', 'Cristal', 'dana', 'ANGEL CARNICERIA', 'america', 'Cliente 16', 'Angel carniceria', 'Ana-paola', 'Tacos-vecino', 'ems morales', 'Elvia ', 'Carla ', 'Brawlio', 'Fransisco ', 'Purisima-11', 'Clienta-48', 'cli purisima 11', 'Eva', 'Mel tacos v', 'Ricardo-Martinez', 'Sr. Jarez', 'jessica ', 'Clienta.17', 'Alejandra-Portales7', 'Hector', 'Fransisco', 'Joahana ', 'Lorena', 'cliente 9b101', 'may rodriguez', 'tacos v', 'Jessica-1b', 'kato', 'KMPE', 'Cliente-15', 'monserrat', 'Sr. Juarez ', 'Mel-vecino', 'Angeles', 'Oscarr ', 'Elvia', 'Jessica-Portales', 'Espinoza', 'Alejandra ', 'Jafet ', 'vianey', 'Soraida', 'Yayo ', 'Jessica cli ', 'Mauricio cli ', 'Fer navarro', 'Johana ', 'Irma '}
